/**
 * POST /api/signup
 *
 * Registers a new artist and creates their first campaign.
 * Called by the signup form on web/index.html.
 *
 * Body:
 *   artist       string  Artist name
 *   song         string  Song title
 *   genre        string  Genre
 *   spotify      string  Spotify URL
 *   description  string  What the song is about (story, theme — used for AI image generation)
 *   mood         string  Mood & feeling of the song (vibe, emotion — used for image gen + hook matching)
 *   email        string  Artist email
 *
 * Hook lines are NOT provided by the artist — RunSound auto-generates them
 * by scanning trending TikTok hooks that match the genre and mood.
 *
 * Response:
 *   { ok: true, slug, smartLinkUrl }
 *   { ok: false, error }
 */
const express  = require('express');
const multer   = require('multer');
const router   = express.Router();

// Multer: memory storage for uploaded reference/own images (max 5MB each, 12 files)
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 5 * 1024 * 1024, files: 12 },
  fileFilter: (req, file, cb) => cb(null, file.mimetype.startsWith('image/')),
});
const crypto   = require('crypto');
const supabase = require('../db');
const { sendWelcomeEmail } = require('../email');

/** Generate a secure random token for dashboard access */
function generateToken() {
  return crypto.randomBytes(32).toString('hex'); // 64-char hex
}

// Slugify: "Carly Rae Jepsen — Summer Love" → "carly-rae-jepsen-summer-love"
function slugify(artist, song) {
  return `${artist}-${song}`
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 80);
}

// Build the campaign config.json structure (used by pipeline scripts)
function buildConfig(data) {
  return {
    artist: {
      name:     data.artist,
      tiktokId: null,  // Connected later via Postiz
    },
    song: {
      title:       data.song,
      genre:       data.genre || 'pop',
      description:     data.description     || '',  // What the song is about — drives image generation
      mood:            data.mood            || '',  // Vibe/feeling — used for hook matching + image style
      lyrics:          data.song_type === 'instrumental' ? '' : (data.lyrics || ''),
      isInstrumental:  data.song_type === 'instrumental',  // true → mood/description drive everything
      targetAudience:  data.target_audience || '',  // Who listens — used by AI to write targeted hooks
      hookLines:       [],                          // Auto-generated by scanning TikTok trends — not artist-provided
    },
    streaming: {
      spotify:    data.spotify    || null,
      apple:      data.apple      || null,
      youtube:    data.youtube    || null,
      tidal:      data.tidal      || null,
      deezer:     data.deezer     || null,
      amazon:     data.amazon     || null,
      soundcloud: data.soundcloud || null,
    },
    imageGen: {
      model:  'gpt-image-2-2026-04-21',
      style:  'candid lifestyle photography, Pinterest aesthetic, authentic iPhone photo, soft natural light',
      count:  2,
      mode:   data.image_mode || 'reference', // reference | own
    },
    posting: {
      schedule: '0 3 * * *',
      timezone: 'Europe/Stockholm',
    },
  };
}

// Middleware: apply multer only for multipart requests, pass through JSON
function smartUpload(req, res, next) {
  const ct = req.headers['content-type'] || '';
  if (ct.includes('multipart/form-data')) {
    return upload.any()(req, res, next);
  }
  next();
}

router.post('/', smartUpload, async (req, res) => {
  try {
    const { artist, song, genre, spotify, description, mood, lyrics, target_audience, email } = req.body;
    const imageMode  = req.body.image_mode || 'reference'; // reference | own
    const imageFiles = req.files || [];

    console.log(`[signup] image_mode=${imageMode}, files=${imageFiles.length}`);

    if (!artist || !song || !email) {
      return res.status(400).json({ ok: false, error: 'artist, song and email are required' });
    }

    // ── 1. Upsert artist ───────────────────────────────────────────────────────
    let artistRow;
    const { data: existingArtist } = await supabase
      .from('artists')
      .select('*')
      .eq('email', email.toLowerCase().trim())
      .single();

    if (existingArtist) {
      artistRow = existingArtist;
    } else {
      const { data: newArtist, error: artistErr } = await supabase
        .from('artists')
        .insert({
          email:  email.toLowerCase().trim(),
          name:   artist,
          plan:   'starter',
          status: 'trial',
        })
        .select()
        .single();

      if (artistErr) throw artistErr;
      artistRow = newArtist;
    }

    // ── 2. Create campaign ─────────────────────────────────────────────────────
    const baseSlug = slugify(artist, song);

    // Ensure slug is unique
    let slug = baseSlug;
    let suffix = 1;
    while (true) {
      const { data: existing } = await supabase
        .from('campaigns')
        .select('id')
        .eq('slug', slug)
        .single();
      if (!existing) break;
      slug = `${baseSlug}-${++suffix}`;
    }

    const config = buildConfig({ artist, song, genre, spotify, description, mood, lyrics, target_audience,
      apple: req.body.apple, youtube: req.body.youtube, tidal: req.body.tidal,
      deezer: req.body.deezer, amazon: req.body.amazon, soundcloud: req.body.soundcloud,
    });
    const BASE         = process.env.BASE_URL || 'https://runsound.fm';
    const smartLinkUrl = `${BASE}/l/${slug}`;

    // Magic-link token — artist uses this to access their dashboard
    // Without it the dashboard shows 401. Token is sent in the welcome email.
    const dashToken = generateToken();

    const { data: campaign, error: campaignErr } = await supabase
      .from('campaigns')
      .insert({
        artist_id:          artistRow.id,
        slug,
        artist_name:        artist,
        song_title:         song,
        genre:              genre          || null,
        mood:               mood           || null,
        spotify_url:        req.body.spotify    || null,
        apple_url:          req.body.apple      || null,
        youtube_url:        req.body.youtube    || null,
        tidal_url:          req.body.tidal      || null,
        deezer_url:         req.body.deezer     || null,
        amazon_url:         req.body.amazon     || null,
        soundcloud_url:     req.body.soundcloud || null,
        hook_lines:         [],
        config,
        smart_link_url:     smartLinkUrl,
        dash_token:         dashToken,
        onboarding_status:  'setup',
        active:             true,
      })
      .select()
      .single();

    if (campaignErr) throw campaignErr;

    // Update config with campaign.id now that we have it (needed by post-to-tiktok.js)
    config.campaign = { id: campaign.id, slug, smartLinkUrl };

    // ── Auto-fetch artwork from Spotify oEmbed ─────────────────────────────────
    let artworkUrl = req.body.artwork_url || null;
    if (!artworkUrl && req.body.spotify) {
      try {
        const { default: fetch } = await import('node-fetch');
        const oembed = await fetch(
          `https://open.spotify.com/oembed?url=${encodeURIComponent(req.body.spotify)}`,
          { headers: { 'User-Agent': 'RunSound/1.0' } }
        );
        if (oembed.ok) {
          const data = await oembed.json();
          artworkUrl = data.thumbnail_url || null;
          console.log(`[signup] Artwork fetched from Spotify: ${artworkUrl}`);
        }
      } catch (e) {
        console.warn('[signup] Could not fetch Spotify artwork:', e.message);
      }
    }

    // ── Upload artist images to Supabase Storage ──────────────────────────────
    const uploadedImageUrls = [];
    if (imageFiles.length > 0 && imageMode !== 'generate') {
      console.log(`[signup] Uploading ${imageFiles.length} ${imageMode} images for campaign ${campaign.id}`);
      for (let i = 0; i < imageFiles.length; i++) {
        const file = imageFiles[i];
        const ext  = file.originalname?.split('.').pop() || 'jpg';
        const path = `${campaign.id}/${imageMode}_${String(i + 1).padStart(2, '0')}.${ext}`;
        const { error: upErr } = await supabase.storage
          .from('artist-images')
          .upload(path, file.buffer, { contentType: file.mimetype, upsert: true });
        if (upErr) {
          console.warn(`[signup] Image upload failed (${path}):`, upErr.message);
        } else {
          const { data: { publicUrl } } = supabase.storage.from('artist-images').getPublicUrl(path);
          uploadedImageUrls.push(publicUrl);
        }
      }
      config.imageGen.uploadedImages = uploadedImageUrls;
      console.log(`[signup] Uploaded ${uploadedImageUrls.length} images`);
    }

    await supabase.from('campaigns').update({
      config,
      ...(artworkUrl ? { artwork_url: artworkUrl } : {}),
    }).eq('id', campaign.id);

    console.log(`[signup] New campaign: ${slug} (artist: ${email}, image_mode: ${imageMode})`);

    // Dashboard URL includes token — this is the artist's personal access link
    const dashboardUrl = `${BASE}/dashboard.html?campaign_id=${campaign.id}&token=${dashToken}`;

    // Send welcome email (non-blocking)
    // Onboarding pipeline is NOT started here — it starts after the artist
    // connects their TikTok account on /connect.html (triggered by /auth/tiktok/callback)
    setImmediate(async () => {
      await sendWelcomeEmail({
        artistName:   artist,
        email:        email.toLowerCase().trim(),
        songTitle:    song,
        dashboardUrl,
        smartLinkUrl,
      });
    });

    return res.json({
      ok:           true,
      slug,
      smartLinkUrl,
      dashboardUrl,
      dashToken,
      campaignId:   campaign.id,
      artistId:     artistRow.id,
    });

  } catch (err) {
    console.error('[signup] Error:', err.message);
    return res.status(500).json({ ok: false, error: 'Something went wrong. Please try again.' });
  }
});

module.exports = router;
